name: qt-2048-snap
base: core18
version: '4.0'
summary: Single player puzzle game.
description: |
  2048 is a single-player puzzle game in which the objective is to slide numbered tiles on
  a grid to combine them and create a tile with the number 2048.

grade: stable 
confinement: strict
icon: snap/gui/icon.png

architectures:
  - build-on: amd64
    run-on: amd64
    
apps:
  qt-2048-snap:
    command: desktop-launch 2048-qt
    environment:
       DISABLE_WAYLAND: 1
    desktop: usr/share/applications/2048.desktop
    plugs:
        - alsa
        - audio-playback
        - browser-support
        - desktop
        - gsettings
        - home
        - opengl
        - desktop-legacy
        - unity7
        #- network
        - wayland
        - x11
plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  qt513:
    interface: content
    target: $SNAP/qt513
    default-provider: qt513
      
parts:
   snap-launcher:
     plugin: dump
     source: snap_launcher/
     override-build: |
            snapcraftctl build
            sed -i 's|Icon=.*|Icon=${SNAP}/meta/gui/icon.png|g' ${SNAPCRAFT_PART_SRC}/2048.desktop
            mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/
            cp -rf ${SNAPCRAFT_PART_SRC}/2048.desktop ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/2048.desktop
